/**
 * AUTO-GENERATED by scripts/gen-renderer-index.js — do not edit manually.
 * To regenerate: node scripts/gen-renderer-index.js
 */
import { registerRenderer } from './registry';
import { manifest as agentInspector } from '@/components/renderers/agent-inspector/manifest';
import { manifest as audio } from '@/components/renderers/audio/manifest';
import { manifest as backlinks } from '@/components/renderers/backlinks/manifest';
import { manifest as changeLog } from '@/components/renderers/change-log/manifest';
import { manifest as config } from '@/components/renderers/config/manifest';
import { manifest as csv } from '@/components/renderers/csv/manifest';
import { manifest as image } from '@/components/renderers/image/manifest';
import { manifest as pdf } from '@/components/renderers/pdf/manifest';
import { manifest as summary } from '@/components/renderers/summary/manifest';
import { manifest as timeline } from '@/components/renderers/timeline/manifest';
import { manifest as todo } from '@/components/renderers/todo/manifest';
import { manifest as video } from '@/components/renderers/video/manifest';
import { manifest as workflowYaml } from '@/components/renderers/workflow-yaml/manifest';
import { manifest as graph } from '@/components/renderers/graph/manifest';

const manifests = [
  agentInspector, audio, backlinks, changeLog, config, csv, image, pdf, summary, timeline, todo, video, workflowYaml, graph,
];

for (const m of manifests) {
  registerRenderer(m);
}
