/**
 * AUTO-GENERATED by scripts/gen-renderer-index.js — do not edit manually.
 * To regenerate: node scripts/gen-renderer-index.js
 */
import { registerRenderer } from './registry';
import { manifest as backlinks } from '@/components/renderers/backlinks/manifest';
import { manifest as config } from '@/components/renderers/config/manifest';
import { manifest as csv } from '@/components/renderers/csv/manifest';
import { manifest as summary } from '@/components/renderers/summary/manifest';
import { manifest as timeline } from '@/components/renderers/timeline/manifest';
import { manifest as todo } from '@/components/renderers/todo/manifest';
import { manifest as workflowYaml } from '@/components/renderers/workflow-yaml/manifest';
import { manifest as graph } from '@/components/renderers/graph/manifest';

const manifests = [
  backlinks, config, csv, summary, timeline, todo, workflowYaml, graph,
];

for (const m of manifests) {
  registerRenderer(m);
}
