/**
 * AUTO-GENERATED by scripts/gen-renderer-index.js — do not edit manually.
 * To regenerate: node scripts/gen-renderer-index.js
 */
import { registerRenderer } from './registry';
import { manifest as agentInspector } from '@/components/renderers/agent-inspector/manifest';
import { manifest as backlinks } from '@/components/renderers/backlinks/manifest';
import { manifest as config } from '@/components/renderers/config/manifest';
import { manifest as csv } from '@/components/renderers/csv/manifest';
import { manifest as diff } from '@/components/renderers/diff/manifest';
import { manifest as graph } from '@/components/renderers/graph/manifest';
import { manifest as summary } from '@/components/renderers/summary/manifest';
import { manifest as timeline } from '@/components/renderers/timeline/manifest';
import { manifest as todo } from '@/components/renderers/todo/manifest';
import { manifest as workflow } from '@/components/renderers/workflow/manifest';

const manifests = [
  agentInspector, backlinks, config, csv, diff, graph, summary, timeline, todo, workflow,
];

for (const m of manifests) {
  registerRenderer(m);
}
