/**
 * Install a `mindos` shell command that delegates to the bundled (or dev) CLI.
 * Does not use npm global install — writes ~/.mindos/bin/mindos and optionally
 * appends PATH to ~/.zshrc (etc.).
 */
import { app, dialog, BrowserWindow, Notification } from 'electron';
import path from 'path';
import {
  mkdirSync,
  writeFileSync,
  chmodSync,
  existsSync,
  readFileSync,
  appendFileSync,
} from 'fs';
import { getDefaultBundledMindOsDirectory } from './mindos-runtime-path';

const SHELL_MARKER = '# MindOS Desktop — CLI (mindos)';

function shimDir(): string {
  return path.join(app.getPath('home'), '.mindos', 'bin');
}

function shimPath(): string {
  return path.join(shimDir(), process.platform === 'win32' ? 'mindos.cmd' : 'mindos');
}

function resolveCliJs(): string | null {
  const bundledRoot = getDefaultBundledMindOsDirectory();
  if (bundledRoot) {
    const p = path.join(bundledRoot, 'bin', 'cli.js');
    if (existsSync(p)) return p;
  }
  if (app.isPackaged) return null;
  const dev = path.join(app.getAppPath(), '..', 'bin', 'cli.js');
  return existsSync(dev) ? dev : null;
}

/** Safe single-quoted literal for POSIX sh. */
function shellSingleQuote(s: string): string {
  return `'${s.replace(/'/g, `'\"'\"'`)}'`;
}

function writeUnixShim(cliJs: string): void {
  const cliLit = shellSingleQuote(cliJs);
  const script = `#!/bin/sh
# Generated by MindOS Desktop — overwritten on each app launch.
CLI=${cliLit}

# If target CLI is missing (e.g. Desktop .app deleted), try npm global fallback
if [ ! -f "$CLI" ]; then
  NPM_ROOT=\$(npm root -g 2>/dev/null)
  NPM_CLI="\${NPM_ROOT}/@geminilight/mindos/bin/cli.js"
  if [ -f "$NPM_CLI" ]; then
    CLI="$NPM_CLI"
  else
    echo "mindos: MindOS Desktop has been removed and no npm global install found." >&2
    echo "" >&2
    echo "  To reinstall CLI:      npm install -g @geminilight/mindos" >&2
    echo "  To clean up residuals:  bash ~/.mindos/uninstall.sh" >&2
    echo "  To reinstall Desktop:   https://mindos.app/download" >&2
    exit 127
  fi
fi

if [ -x "$HOME/.mindos/node/bin/node" ]; then
  exec "$HOME/.mindos/node/bin/node" "$CLI" "$@"
fi
if command -v node >/dev/null 2>&1; then
  exec node "$CLI" "$@"
fi
echo "mindos: Node.js not found. Open MindOS Desktop once (it installs Node under ~/.mindos/node), or install Node 18+." >&2
exit 127
`;
  const out = shimPath();
  mkdirSync(shimDir(), { recursive: true });
  writeFileSync(out, script, 'utf-8');
  try {
    chmodSync(out, 0o755);
  } catch {
    /* ignore */
  }
}

function writeWindowsShim(cliJs: string): void {
  const nodePrivate = path.join(app.getPath('home'), '.mindos', 'node', 'node.exe');
  const cliEsc = cliJs.replace(/"/g, '""');
  const privEsc = nodePrivate.replace(/"/g, '""');
  const lines = [
    '@echo off',
    'setlocal',
    `set "CLI=${cliEsc}"`,
    'if not exist "%CLI%" (',
    '  for /f "delims=" %%i in (\'npm root -g 2^>nul\') do set "NPM_CLI=%%i\\@geminilight\\mindos\\bin\\cli.js"',
    '  if exist "%NPM_CLI%" ( set "CLI=%NPM_CLI%" ) else (',
    '    echo mindos: MindOS Desktop has been removed. Reinstall: npm install -g @geminilight/mindos >&2',
    '    exit /b 127',
    '  )',
    ')',
    `if exist "${privEsc}" (`,
    `  "${privEsc}" "%CLI%" %*`,
    '  exit /b %ERRORLEVEL%',
    ')',
    'where node >nul 2>&1 || (echo mindos: Node.js not found. Open MindOS Desktop or install Node 18+. >&2 & exit /b 127)',
    'node "%CLI%" %*',
  ];
  mkdirSync(shimDir(), { recursive: true });
  writeFileSync(shimPath(), lines.join('\r\n'), 'utf-8');
}

/** Append ~/.mindos/bin to PATH in the first matching shell rc (idempotent). Returns true if we appended. */
function appendMindosBinToShellRc(): boolean {
  if (process.platform === 'win32') return false;

  const home = app.getPath('home');
  const block = `\n${SHELL_MARKER}\nexport PATH="$HOME/.mindos/bin:$PATH"\n`;

  const order =
    process.platform === 'darwin'
      ? ['.zshrc', '.zprofile', '.bash_profile', '.bashrc']
      : ['.bashrc', '.zshrc', '.profile'];

  for (const name of order) {
    const full = path.join(home, name);
    if (existsSync(full) && readFileSync(full, 'utf-8').includes(SHELL_MARKER)) {
      return false;
    }
  }

  for (const name of order) {
    const full = path.join(home, name);
    if (!existsSync(full)) continue;
    appendFileSync(full, block, 'utf-8');
    return true;
  }

  const fallback = path.join(home, process.platform === 'darwin' ? '.zshrc' : '.bashrc');
  appendFileSync(fallback, block, 'utf-8');
  return true;
}

/** Generate ~/.mindos/uninstall.sh for cleanup after .app deletion */
function writeUninstallScript(): void {
  if (process.platform === 'win32') return; // TODO: uninstall.bat

  const home = app.getPath('home');
  const script = `#!/bin/sh
# MindOS Cleanup Script
# Generated by MindOS Desktop — cleans up residual files after app deletion.
# Your knowledge base (~/MindOS/mind) is NOT touched.

set -e
echo "MindOS Cleanup"
echo ""

# 1. Kill running MindOS processes
for pid_file in "$HOME/.mindos/mindos.pid" "$HOME/.mindos/desktop-children.pid"; do
  if [ -f "$pid_file" ]; then
    while IFS= read -r pid; do
      kill "$pid" 2>/dev/null && echo "  Stopped process $pid" || true
    done < "$pid_file"
    rm -f "$pid_file"
  fi
done

# 2. Remove private Node.js (~220MB)
if [ -d "$HOME/.mindos/node" ]; then
  echo "  Removing private Node.js..."
  rm -rf "$HOME/.mindos/node"
fi

# 3. Remove CLI shim
rm -f "$HOME/.mindos/bin/mindos"
rmdir "$HOME/.mindos/bin" 2>/dev/null || true

# 4. Clean PATH injection from shell rc files
for rc in "$HOME/.zshrc" "$HOME/.zprofile" "$HOME/.bash_profile" "$HOME/.bashrc" "$HOME/.profile"; do
  if [ -f "$rc" ] && grep -q '# MindOS Desktop' "$rc"; then
    # Remove the marker line and the export line that follows it
    if [ "\$(uname)" = "Darwin" ]; then
      sed -i '' '/# MindOS Desktop/,+1d' "$rc"
    else
      sed -i '/# MindOS Desktop/,+1d' "$rc"
    fi
    echo "  Cleaned $rc"
  fi
done

# 5. Note MCP client configs that still reference MindOS
for cfg in "$HOME/.claude.json" "$HOME/.cursor/mcp.json" "$HOME/.codeium/windsurf/mcp_config.json"; do
  if [ -f "$cfg" ] && grep -q "mindos" "$cfg"; then
    echo "  Note: $cfg still references MindOS — remove the 'mindos' entry manually."
  fi
done

# 6. Remove config and state files
rm -f "$HOME/.mindos/config.json"
rm -f "$HOME/.mindos/stdin-watchdog.cjs"
rm -f "$HOME/.mindos/desktop-cli-path-notify-v1"
rm -f "$HOME/.mindos/update-status.json"
rm -f "$HOME/.mindos/ssh-tunnel.pid"
rm -rf "$HOME/.mindos/tmp"
rm -rf "$HOME/.mindos/sessions"

# 7. Remove Electron app data (macOS)
if [ "\$(uname)" = "Darwin" ]; then
  rm -rf "$HOME/Library/Application Support/MindOS"
  rm -rf "$HOME/Library/Caches/com.geminilight.mindos"
  rm -f "$HOME/Library/Preferences/com.geminilight.mindos.plist"
fi

# 8. Self-remove
rm -f "$HOME/.mindos/uninstall.sh"
rmdir "$HOME/.mindos" 2>/dev/null || true

echo ""
echo "Done. Your knowledge base was NOT touched."
echo "To also remove it: rm -rf ~/MindOS/mind"
`;

  const scriptPath = path.join(home, '.mindos', 'uninstall.sh');
  if (existsSync(scriptPath)) return; // idempotent — only create once
  try {
    mkdirSync(path.dirname(scriptPath), { recursive: true });
    writeFileSync(scriptPath, script, 'utf-8');
    chmodSync(scriptPath, 0o755);
  } catch { /* best effort */ }
}

const NOTIFY_FLAG = 'desktop-cli-path-notify-v1';

function notifyFlagPath(): string {
  return path.join(app.getPath('home'), '.mindos', NOTIFY_FLAG);
}

function showMessageBoxSafe(
  parent: BrowserWindow | null | undefined,
  options: Electron.MessageBoxOptions,
): void {
  const win = parent && !parent.isDestroyed() ? parent : null;
  if (win) void dialog.showMessageBox(win, options);
  else void dialog.showMessageBox(options);
}

/** One-time hint after ~/.mindos/bin is appended to shell rc — banner, not a blocking dialog. */
function notifyPathAppendedOnce(): void {
  if (existsSync(notifyFlagPath())) return;
  try {
    writeFileSync(notifyFlagPath(), new Date().toISOString(), 'utf-8');
  } catch {
    /* still try notification */
  }

  const zh = app.getLocale()?.toLowerCase().startsWith('zh');
  const title = zh ? 'mindos 命令行已就绪' : 'mindos CLI is ready';
  const body = zh
    ? '已写入 ~/.mindos/bin 并加入 PATH。请新开终端后运行 mindos --help'
    : '~/.mindos/bin added to PATH. Open a new terminal, then run mindos --help';

  if (Notification.isSupported()) {
    try {
      new Notification({ title, body }).show();
      return;
    } catch {
      /* fall through */
    }
  }
  console.info(`[MindOS] ${title} — ${body}`);
}

/**
 * Sync shim on disk. Call on each launch so CLI tracks the current .app location.
 * Optionally append PATH once; first PATH change triggers a one-time OS notification (no modal).
 */
export function ensureMindosCliShim(opts?: {
  /** default true on macOS/Linux */
  appendPath?: boolean;
}): { ok: boolean; error?: string } {
  const cliJs = resolveCliJs();
  if (!cliJs) {
    const msg =
      'Bundled MindOS CLI not found (mindos-runtime/bin/cli.js). Reinstall the app or run from a built repo.';
    console.error('[MindOS]', msg);
    return { ok: false, error: msg };
  }

  try {
    if (process.platform === 'win32') writeWindowsShim(cliJs);
    else writeUnixShim(cliJs);
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error('[MindOS] Failed to write CLI shim:', msg);
    return { ok: false, error: msg };
  }

  const doAppend = opts?.appendPath !== false && process.platform !== 'win32';
  let appended = false;
  if (doAppend) {
    try {
      appended = appendMindosBinToShellRc();
    } catch (e) {
      console.warn('[MindOS] Could not append PATH to shell rc:', e);
    }
  }

  if (appended) notifyPathAppendedOnce();

  writeUninstallScript();

  console.info('[MindOS] CLI shim:', shimPath(), '→', cliJs);
  return { ok: true };
}

/** Tray / manual: refresh shim + show result (and Windows PATH hint). */
export function refreshMindosCliAndNotify(parent: BrowserWindow | null): void {
  const r = ensureMindosCliShim({ appendPath: true });
  const zh = app.getLocale()?.toLowerCase().startsWith('zh');
  if (r.ok) {
    if (process.platform === 'win32') {
      showMessageBoxSafe(parent, {
        type: 'info',
        title: zh ? 'mindos 命令' : 'mindos command',
        message: zh
          ? `已更新 ${shimPath()}。请将以下目录加入系统 PATH 后新开终端：`
          : `Updated ${shimPath()}. Add this folder to your user PATH, then open a new terminal:`,
        detail: shimDir(),
      });
    } else {
      showMessageBoxSafe(parent, {
        type: 'info',
        title: zh ? 'mindos 命令' : 'mindos command',
        message: zh
          ? '已更新 ~/.mindos/bin/mindos。若终端仍提示找不到命令，请新开终端窗口，或执行 source ~/.zshrc。'
          : 'Updated ~/.mindos/bin/mindos. Open a new terminal or run source ~/.zshrc if the command is not found.',
        detail: shimPath(),
      });
    }
    return;
  }
  showMessageBoxSafe(parent, {
    type: 'error',
    title: zh ? 'mindos 安装失败' : 'mindos install failed',
    message: r.error ?? 'Unknown error',
  });
}
